### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by r3tard3dd** [samfromaway/firebase-tutorial#1]
I get this error : 
Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
when I am currently logged in and try to go back to login page.
I used exactly the same code in the boilerplate

**Comment by samfromaway** [comment]
Yes, there will be many errors with the login function. This was just for the tutorial. 
For a real application for examples, you would want to hide the login/register form as soon as somebody is logged in.
For example:
`return (
  {!currentUser && <LoginRegisterComponent />}
  {currentUser && <Dashboard />}
)`

This would show the Dashboard when logged in and the Register Form when logged out.

Another thing I usually do is add a listener to the loginChange function. Maybe I will do a tutorial about that soon.
